download_dir = "downloads"

[sources]

[sources.string]
[sources.string.human_physical_links_min900]
filename = "9606.protein.physical.links.v12.0.min900.onlyAB.csv"
url = "https://stringdb-downloads.org/download/stream/protein.physical.links.v12.0/9606.protein.physical.links.v12.0.min900.onlyAB.csv.gz"

