name: network_preparation
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.12
  - conda-forge::pandas=2.2
  - conda-forge::numpy=2.1
  - conda-forge::scipy=1.14
  - conda-forge::toml=0.10.2
  - conda-forge::graph-tool=2.77
  - conda-forge::networkx=3.3
  - bioconda::nedrex=0.1.4
  - pip
  - pip:
    - pyintergraph==1.3.3
    - drugstone==0.4.5
    - mygene==3.0.0

